//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_loanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountTable()
        {
            this.Transaction_Table = new HashSet<Transaction_Table>();
            this.UserTables = new HashSet<UserTable>();
        }
    
        public int Account_Id { get; set; }
        public string Account_name { get; set; }
        public string Account_SortCode { get; set; }
        public string Account_number { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Table> Transaction_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTable> UserTables { get; set; }
    }
}
