//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_loanApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eLoan_ApplicationEntities1 : DbContext
    {
        public eLoan_ApplicationEntities1()
            : base("name=eLoan_ApplicationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTable> AccountTables { get; set; }
        public virtual DbSet<RoleMappingTable> RoleMappingTables { get; set; }
        public virtual DbSet<RoleTable> RoleTables { get; set; }
        public virtual DbSet<Transaction_Table> Transaction_Table { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
