//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_loanApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Table
    {
        public int Txn_Id { get; set; }
        public string Receiver_Account_name { get; set; }
        public string Receiver_Email { get; set; }
        public string Receiver_SortCode { get; set; }
        public string Transaction_Des { get; set; }
        public string Reciever_Accountnum { get; set; }
        public string TXN_REF { get; set; }
        public Nullable<int> OpenPayUserId { get; set; }
        public string Transaction_Purpose { get; set; }
        public string Transaction_status { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string Receiver_Bank { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Transaction_Approved { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<int> account_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Role_Level { get; set; }
    
        public virtual AccountTable AccountTable { get; set; }
        public virtual Transaction_Table Transaction_Table1 { get; set; }
        public virtual Transaction_Table Transaction_Table2 { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
