//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_loanApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {

            this.AccountTables = new HashSet<AccountTable>();

            this.RoleMappingTables = new HashSet<RoleMappingTable>();

            this.Transaction_Table = new HashSet<Transaction_Table>();
        }

        public int UserId { get; set; }
        public string User_First_Name { get; set; }
        public string User_Last_Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string sortCode { get; set; }
        public string acctNumber { get; set; }
        public string StudentPicture { get; set; }
        public string Bank { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Phone_Number { get; set; }
        public string Email_Address { get; set; }
        public string Name_Of_College { get; set; }
        public string Name_Of_Faculty { get; set; }
        public string Programme_Of_Study { get; set; }

        public string Student_Number { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        [NotMapped]
        public HttpPostedFileBase PictureToUpload { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTable> AccountTables { get; set; }
        public virtual AccountTable AccountTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMappingTable> RoleMappingTables { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Table> Transaction_Table { get; set; }
    }
}


